### ISSUE TITLE
Show errors after submitting and not touched

### ISSUE THREAD

**Issue by jilfrance** [crhistianramirez/react-hook-form-chakra#1]
Currently submitting does not show errors when field is not touched. Is that intended ?

If not, we should check if `fieldState.invalid` is `true` in `FormControl`. Let me know if you need a PR

Thank you for this package

**Comment by crhistianramirez** [comment]
Hey! Thanks for reporting this issue, I will take a look at this more deeply on Monday

**Comment by crhistianramirez** [comment]
@jilfrance This issue has been fixed, and is released in version 1.0.1. Thanks again for reporting it
