### ISSUE TITLE
Prop Default Values

### ISSUE THREAD

**Issue by vawogbemi** [crhistianramirez/react-hook-form-chakra#2]
Is there a way to set default values for components through props that will be passed on submission?

I'm able to set default values visually through using inputProps={{defaultValue: value}} or through checkBoxProps={{ defaultChecked: value }} but on submissions the values don't get submit so I'm wondering if theres a way so I can avoid making a default values variable and passing it to the useForm hook.

I want to use inProp default values because I'm generating dynamic components.

**Comment by crhistianramirez** [comment]
@vawogbemi this is a reasonable ask and seems simple enough to implement. Give me a few days and I'll get the library updated and publish a new version

**Comment by crhistianramirez** [comment]
This should be resolved under 1.0.2 https://github.com/crhistianramirez/react-hook-form-chakra/releases/tag/1.0.2
