### ISSUE TITLE
When marking fields as required, isRequired does not get set to true in the formControl

### ISSUE THREAD

**Issue by jay-babu** [crhistianramirez/react-hook-form-chakra#3]
![image](https://github.com/crhistianramirez/react-hook-form-chakra/assets/36803168/9e5a9120-c0ff-4d85-a924-5b3c6dd83f07)

FormControl is still false

**Comment by crhistianramirez** [comment]
@jay-babu It seems to be working for me.

Here are my attempted repro steps:
1. Navigate to [codesandbox demo](https://codesandbox.io/p/devbox/react-hook-form-chakra-0yl36k?file=%2Fsrc%2FFormWithProvider.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A58%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A57%7D%5D)
2. Click on first field (First Name)
3. Click out of the field without typing anything
4. Observe input is outlined red with the text "First Name is required"

<img width="593" alt="Screen Shot 2024-03-27 at 9 55 15 PM" src="https://github.com/crhistianramirez/react-hook-form-chakra/assets/16483662/b75b18cf-b44a-45d7-88a6-7881fe7c826b">

**Comment by crhistianramirez** [comment]
Feel free to re-open if you can provide repro steps
